[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[tool.uv]
# `uv run`するときにuvがe2kをデフォルト設定でビルドしようとするので、それを阻止する。
package = false

[project]
name = "voicevox_e2k"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version"]
dependencies = []

[dependency-groups]
dev = [
  "maturin[patchelf]>=1.8.2",
  "pytest>=8.3.5",
  "ruff>=0.11.0",
  "pytest-benchmark>=4.0.0",
]
