[project]
name = "tools"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = []

[tool.pyright]
typeCheckingMode = "standard"

[dependency-groups]
dev = [
    "pyright>=1.1.397",
    "ruff>=0.11.2",
]
