# 英単語の取得方法を指定します。
sourceProvider: cmudict
# 読みの取得方法を指定します。
inferenceProvider: gemini

# Geminiの設定。
gemini:
  # Google AI Studioから取得したAPIキー。
  apiKey: ""

  # 使うモデルの名前。
  modelName: "gemini-2.0-flash"
