# pnpm run tools:generateConfigSchema で生成。手動で編集しないでください。
type: object
properties:
  randomSeed:
    type: number
  source:
    type: object
    properties:
      provider:
        type: string
        enum:
          - cmudict
      maxNumWords:
        anyOf:
          - type: number
          - type: string
            const: all
    required:
      - provider
      - maxNumWords
    additionalProperties: false
  inference:
    type: object
    properties:
      provider:
        type: string
        enum:
          - gemini
          - openai
      concurrency:
        type: number
      rateLimit:
        type: object
        properties:
          waitMs:
            type: number
          maxRetries:
            type: number
          throttleMs:
            type: number
        required:
          - waitMs
          - maxRetries
          - throttleMs
        additionalProperties: false
      gemini:
        type: object
        properties:
          apiKey:
            type: string
          modelName:
            type: string
        required:
          - apiKey
          - modelName
        additionalProperties: false
      openai:
        type: object
        properties:
          apiBaseUrl:
            type: string
          apiKey:
            type: string
          modelName:
            type: string
        required:
          - apiBaseUrl
          - apiKey
          - modelName
        additionalProperties: false
    required:
      - provider
      - concurrency
      - rateLimit
    additionalProperties: false
required:
  - randomSeed
  - source
  - inference
additionalProperties: false
$schema: http://json-schema.org/draft-07/schema#
