version: "3"

tasks:
  train-cpu:
    cmds:
      - uv run python3 train.py {{.CLI_ARGS}}
  train-cuda:
    cmds:
      - uv run --no-group cpu --group cuda python3 train.py {{.CLI_ARGS}}

  setup-eval:
    cmds:
      - uv run python3 setup_eval.py {{.CLI_ARGS}}

  eval-cpu:
    cmds:
      - uv run python3 eval.py {{.CLI_ARGS}}

  eval-cuda:
    cmds:
      - uv run --no-group cpu --group cuda python3 eval.py {{.CLI_ARGS}}

  merge:
    cmds:
      - uv run python3 merge.py {{.CLI_ARGS}}

  tensorboard:
    cmds:
      - uv run tensorboard --logdir runs {{.CLI_ARGS}}

  export:
    cmds:
      - uv run python3 export.py {{.CLI_ARGS}}

  lint:
    cmds:
      - uv run ruff check *.py {{.CLI_ARGS}}

  fmt:
    cmds:
      - uv run ruff format *.py {{.CLI_ARGS}}
