name: Release Infer
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
      production:
        description: "Release to PyPI (not TestPyPI)"
        required: false
        default: "false"

defaults:
  run:
    shell: bash
    working-directory: infer

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Replace version
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const version = ${{ toJson(inputs.version) }};
            const cargoToml = fs.readFileSync('./infer/crates/e2k-py/Cargo.toml', 'utf8');
            const replacedCargoToml = cargoToml.replace(/version = ".*"/, `version = "${version}"`);
            fs.writeFileSync('./infer/crates/e2k-py/Cargo.toml', replacedCargoToml);

      - name: Run Python build
        working-directory: infer/crates/e2k-py
        run: |
          uv run maturin build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: e2k-py-${{ runner.os }}
          path: infer/target/wheels/*.whl

  publish:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.production == 'true' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
