name: Release Infer
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

defaults:
  run:
    shell: bash
    working-directory: infer

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run Python build
        working-directory: infer/crates/e2k-py
        run: |
          uv run maturin build --release

      - name: Get information
        id: info
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = ${{ toJson(github.event.inputs.version) }};
            core.setOutput('prerelease', version.includes('-'));

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: infer/target/wheels/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.event.inputs.version }}
          release_tag: ${{ github.event.inputs.version }}
          prerelease: ${{ steps.info.outputs.prerelease }}
