name: Release Infer
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
      production:
        description: "Release to PyPI (not TestPyPI)"
        required: false
        default: "false"

defaults:
  run:
    shell: bash
    working-directory: infer

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-13
          - windows-2019
          - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Setup cargo-about
        run: cargo binstall cargo-about

      - name: Setup windows i686
        if: matrix.os == 'windows-2019'
        run: rustup target add i686-pc-windows-msvc

      - name: Build wheel
        working-directory: infer/tools
        run: |
          uv run build_e2k_py.py --wheel --version ${{ inputs.version }}

      - name: Build sdist
        working-directory: infer/tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          uv run build_e2k_py.py --sdist --version ${{ inputs.version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: e2k-py-${{ matrix.os }}
          path: |
            infer/target/wheels/*.whl
            infer/target/wheels/*.tar.gz

  publish:
    needs:
      - build

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    environment: release

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: e2k-py-*
          merge-multiple: true
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.production == 'true' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
          verbose: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          body: |
            Release v${{ inputs.version }}
          draft: false
          prerelease: ${{ inputs.production != 'true' }}
