name: Test Train
on:
  push:
  pull_request:
    paths:
      - .github/workflows/test_train.yml
      - train

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run lint
        working-directory: train
        run: |
          uv run ruff check
          uv run ruff format --diff
