name: Test Train
on:
  push:
  pull_request:
    paths:
      - .github/workflows/test_train.yml
      - train/**

defaults:
  run:
    working-directory: train

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run lint
        run: |
          uv run ruff check
          uv run ruff format --diff
